build_cloud: MacBook-Pro-de-Matheus.local
image:
- Visual Studio 2019
- macOS

environment:
  nodejs_version: "18"

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run release

test: off
