name: Release new version
on:
  #release:
   # types: [created]
   # paths-ignore:
   #   - "**.md"
   #   - "**.yml"

  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: npm install
        run: |
          npm install

      - name: npm release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          APP_INSIGHTS_INSTRUMENTATION_KEY: ${{ secrets.APP_INSIGHTS_INSTRUMENTATION_KEY }}
          CSC_LINK: ${{ secrets.APPLE_CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.APPLE_CSC_KEY_PASSWORD }}
          CSC_INSTALLER_LINK: ${{ secrets.APPLE_CSC_INSTALLER_LINK }}
          CSC_INSTALLER_KEY_PASSWORD: ${{ secrets.APPLE_CSC_INSTALLER_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASSWORD }}

        run: |
          npm run release
