name: Release new version
on:
   release:
     types: [created]
     paths-ignore:
       - "**.md"
       - "**.yml"
       - ".vscode/**"
       - ".gitignore"
       - ".gitattributes"
       - "LICENSE"
       - ".editorconfig"

  # push:
  #   branches:
  #     - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: npm install
        run: |
          npm install

      - name: npm postinstall
        run: |
          npm run postinstall

      - name: Set macOS certificate for code signing
        if: matrix.os == 'macos-latest'
        env:
          CSC_LINK: ${{ secrets.APPLE_CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.APPLE_CSC_KEY_PASSWORD }}
          CSC_INSTALLER_LINK: ${{ secrets.APPLE_CSC_INSTALLER_LINK }}
          CSC_INSTALLER_KEY_PASSWORD: ${{ secrets.APPLE_CSC_INSTALLER_KEY_PASSWORD }}
        run: |
          echo "CSC_LINK=${{ secrets.APPLE_CSC_LINK }}" >> $GITHUB_ENV
          echo "CSC_KEY_PASSWORD=${{ secrets.APPLE_CSC_KEY_PASSWORD }}" >> $GITHUB_ENV
          echo "CSC_INSTALLER_LINK=${{ secrets.APPLE_CSC_INSTALLER_LINK }}" >> $GITHUB_ENV
          echo "CSC_INSTALLER_KEY_PASSWORD=${{ secrets.APPLE_CSC_INSTALLER_KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Set Environment Variables
        run: |
          echo "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" >> $GITHUB_ENV
          echo "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> $GITHUB_ENV
          echo "AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}" >> $GITHUB_ENV
          echo "APTABASE_APP_KEY=${{ secrets.APTABASE_APP_KEY }}" >> $GITHUB_ENV
          echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> $GITHUB_ENV
          echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> $GITHUB_ENV
          echo "SENTRY_DSN_RENDERER=${{ secrets.SENTRY_DSN_RENDERER }}" >> $GITHUB_ENV
      - name: npm release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          APTABASE_APP_KEY: ${{ secrets.APTABASE_APP_KEY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_DSN_RENDERER: ${{ secrets.SENTRY_DSN_RENDERER }}
        run: |
          npm run release
