name: Release new version
on: 
  push:
    branches: ["main"]
    paths-ignore:
      - "**.md"
      - "**.yml"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.14, windows-2019, ubuntu-18.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: npm install
        run: |
          npm install

      - name: npm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          APP_INSIGHTS_INSTRUMENTATION_KEY: ${{ secrets.APP_INSIGHTS_INSTRUMENTATION_KEY }}
          
        run: |
          npm run release-debug
